let directionsService, directionsRenderer, placesService;
window.initIndiaRoadPlannerMaps = function(){
  if(!window.google?.maps) return;
  directionsService = new google.maps.DirectionsService();
  const mapNode=document.querySelector('#route-map');
  if(mapNode){const map=new google.maps.Map(mapNode,{center:{lat:22.5,lng:79},zoom:5,mapTypeControl:true,streetViewControl:false});directionsRenderer=new google.maps.DirectionsRenderer({map,preserveViewport:false});placesService=new google.maps.places.PlacesService(map);}
};
export function initPlanner(){const form=document.querySelector('#route-form');if(!form)return;const result=document.querySelector('#route-result');const show=t=>{result.textContent=t;result.classList.remove('hidden')};
const kmInput=form.elements.km, hoursInput=form.elements.hours;
function nearby(latLng){const box=document.querySelector('#nearby-results');if(!box||!placesService)return;box.innerHTML='<p>Finding nearby attractions…</p>';placesService.nearbySearch({location:latLng,radius:50000,type:'tourist_attraction'},(items,status)=>{if(status!==google.maps.places.PlacesServiceStatus.OK||!items?.length){box.innerHTML='<p>No nearby attractions returned. Try a larger destination or search Google Maps.</p>';return;}box.innerHTML=items.slice(0,10).map(p=>`<article class="destination-result"><span class="pill">Nearby attraction</span><h3>${escapeText(p.name)}</h3><p>${escapeText(p.vicinity||'Near your destination')}</p><a class="text-link" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name+' '+(p.vicinity||''))}">View on Google Maps ↗</a></article>`).join('');});}
function escapeText(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),from=String(d.get('from')).trim(),to=String(d.get('to')).trim(),mode=d.get('mode'),days=Number(d.get('days')),eff=Number(d.get('efficiency')),price=Number(d.get('price'));if(!from||!to||days<1){show('Enter a start, destination and at least one day.');return;}if(!directionsService){show('Google Maps is not configured yet. Add your restricted API key in js/maps-config.js and enable Maps JavaScript API, Places API and Directions service.');return;}const travelMode=mode==='bike'?google.maps.TravelMode.TWO_WHEELER:mode==='walk'?google.maps.TravelMode.WALKING:mode==='transit'?google.maps.TravelMode.TRANSIT:google.maps.TravelMode.DRIVING;show('Calculating route with Google Maps…');directionsService.route({origin:from,destination:to,travelMode,provideRouteAlternatives:false},(route,status)=>{if(status!== 'OK'||!route?.routes?.[0]){show('Google Maps could not calculate this route ('+status+'). Check the place names or travel mode.');return;}directionsRenderer?.setDirections(route);const legs=route.routes[0].legs;const meters=legs.reduce((s,l)=>s+(l.distance?.value||0),0),seconds=legs.reduce((s,l)=>s+(l.duration?.value||0),0),km=meters/1000,hours=seconds/3600;kmInput.value=km.toFixed(1);hoursInput.value=hours.toFixed(1);const fuelModes=mode==='bike'||mode==='car';const litres=fuelModes&&eff>0?km/eff:null,cost=litres!==null?litres*price:null;show(`${from} → ${to}\nGoogle Maps route distance: ${km.toFixed(1)} km\nEstimated driving time: ${hours.toFixed(1)} hours (route estimate; traffic may change)\nTrip duration entered: ${days} days\n${litres!==null?`Estimated fuel required: ${litres.toFixed(2)} L\nEstimated fuel cost: ${cost.toFixed(2)} (same currency as fuel price)\n`:''}Average distance per trip day: ${(km/days).toFixed(1)} km/day\nUse the map and check live road conditions before departure.`);const end=legs[legs.length-1]?.end_location;if(end)nearby(end);});});
const open=document.querySelector('#open-map');open?.addEventListener('click',()=>{const f=form.elements.from.value.trim(),t=form.elements.to.value.trim();if(f&&t)window.open(`https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(f)}&destination=${encodeURIComponent(t)}&travelmode=driving`,'_blank','noopener');else show('Enter both a start and destination first.');});}
